### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by Kostronor** [busyorg/sc2#44]
Currently regardless of what the error is, this gets shown:

![image](https://user-images.githubusercontent.com/644950/28705357-b4fbefb6-736f-11e7-9edd-28afd4e2ad17.png)

Sadly most users are not technically versed enough to open their developer console to see the actual error. So we have many users who want to use steemconnect but get random errors we don't know about.

Is there a way to add the details in a hidden box or so that can be opened up?

**Comment by bonustrack** [comment]
There is now a more detailed error message. Example with the operation `delegate_vesting_shares`: 
![image](https://user-images.githubusercontent.com/16245250/28719350-d8a10a64-73d3-11e7-9d57-e052a8d6a8fe.png)

**Comment by Kostronor** [comment]
That is really helpful, thank you very much @bonustrack
